spring.application.name=ParkingFlow

#Puerto app
server.port = 8081

spring.datasource.url=jdbc:postgresql://localhost:5432/parkingflow
spring.datasource.username=postgres
spring.datasource.password=x121212x.Mazo
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

#JWT
jwt.secret=f6dba95a88d2c100b4647194c35df7475b7b3a487631ac5b40ae015a71962517
jwt.expiration=3600000
jwt.refresh-expiration=86400000

springdoc.api-docs.path=/v3/api-docs
springdoc.api-docs.enabled=true
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.enabled=true
springdoc.swagger-ui.try-it-out-enabled=true
springdoc.swagger-ui.operations-sorter=alpha
springdoc.swagger-ui.tags-sorter=alpha
springdoc.swagger-ui.doc-expansion=none